steps:
  # dbtを実行するためのDockerfileのコンテナイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/dbt-docker-repo/dbt-transform",
        # "--build-arg",
        # "env=$_ENV",
        "."
      ]
  # GARにpush
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/dbt-docker-repo/dbt-transform"]
  # Cloud Run Jobsにデプロイ(定期的にデプロイする都合上updateにしているので事前にコンソールから同名同リージョンのjobを定義しておくと良いです)
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "jobs",
        "update",
        "dbt-transform",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/dbt-docker-repo/dbt-transform",
        "--command",
        "bash",
        "--args",
        "scripts/dbt_build.sh",
        "--region",
        "asia-northeast1",
        "--max-retries",
        "1",
        "--task-timeout",
        "3600s",
      ]
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/dbt-docker-repo/dbt-transform"
options:
  # Cloud BuildはデフォルトでCloud Storageにビルドログを保存しようとするが、
  # Cloud Loggingだけにするように指定
  logging: CLOUD_LOGGING_ONLY
